package:
  name: "tandemmapper2"
  version: "2.0.0"

source:
  # Relative path to the parent directory.
  path: ..

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --ignore-installed --no-deps
  # script: make install PREFIX=${PREFIX}

requirements:
  host:
    - python
    - setuptools
    - zlib

  build:
    - gcc_linux-64==9.4.0  # [linux]
    - gxx_linux-64==9.4.0  # [linux]
    - llvm # [osx]
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - make
    - cmake

  run:
    - python
    - python-slugify
    - biopython
    - click
    - numpy
    - plotly
    - zlib

test:
  commands:
    - tandemmapper2 --help 

about:
  home: https://github.com/ablab/TandemMapper2
  license: GPLv3
